"""MQTT callbacks for the Roomba+ integration.

Handles all push-based state updates from the robot:
  - Mission lifecycle detection (start → end phase transitions)
  - MissionStore record building and persistence
  - Map-retrain detection via user_pmapv_id changes
  - L3 runtime error state updates

Extracted from __init__.py (v2.0 refactor).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import datetime
import logging
from typing import TYPE_CHECKING, Any

from homeassistant.util import dt as dt_util

if TYPE_CHECKING:
    from homeassistant.config_entries import ConfigEntry
    from .cloud_coordinator import IrobotCloudCoordinator
    from .models import RoombaConfigEntry, RoombaData

_LOGGER = logging.getLogger(__name__)

_CLEANING_PHASES: frozenset[str] = frozenset(
    {"run", "hmMidMsn", "hmPostMsn", "hmUsrDock", "evac"}
)
_MISSION_END_PHASES: frozenset[str] = frozenset(
    {"completed", "cancelled", "charge", "stop"}
)


# ── Zone-name capture ─────────────────────────────────────────────────────────

def _capture_zone_names(
    entry: RoombaConfigEntry,
    reported: dict[str, Any],
) -> list[str]:
    """Resolve zone names at mission start for all robot types."""
    from .models import MapCapability

    data: RoombaData = entry.runtime_data
    if data.zone_store:                          # EPHEMERAL
        return [z.name for z in data.zone_store.zones if z.confirmed]
    if data.map_capability == MapCapability.SMART:
        last_cmd = reported.get("lastCommand", {})
        region_ids = [
            r.get("region_id")
            for r in (last_cmd.get("regions") or [])
            if r.get("region_id")
        ]
        if region_ids and data.cloud_coordinator:
            id_to_name = {
                r["id"]: r["name"]
                for r in data.cloud_coordinator.regions
                if r.get("id")
            }
            return [id_to_name[rid] for rid in region_ids if rid in id_to_name]
    return []  # NONE (600-series) or SMART without cloud


# ── Mission record builder ────────────────────────────────────────────────────

async def async_record_mission(
    hass: Any,
    entry: RoombaConfigEntry,
    mission: dict[str, Any],
    reported: dict[str, Any],
    zones: list[str],
    start_ts: int,
    nstuck_delta: int,
) -> None:
    """Build and append a mission record to MissionStore.

    Args:
        hass:         HomeAssistant instance (for storage and dt_util).
        entry:        Config entry whose runtime_data holds the MissionStore.
        mission:      cleanMissionStatus dict from the end-of-mission MQTT message.
        reported:     Full reported state dict from the same MQTT message.
        zones:        Zone names captured at mission START (not end).
        start_ts:     mssnStrtTm cached at mission START. The 980/900-series
                      firmware resets this field to 0 in the end MQTT message,
                      so it must be captured when the cleaning phase begins.
        nstuck_delta: bbrun.nStuck delta since mission start. Using the delta
                      rather than the lifetime counter prevents marking every
                      mission as stuck when bbrun arrives in the same packet.
    """
    data: RoombaData = entry.runtime_data
    if data.mission_store is None:
        return

    now = dt_util.utcnow()

    if start_ts:
        started_at = datetime.datetime.fromtimestamp(
            start_ts, datetime.timezone.utc
        )
    else:
        # Fallback: wall-clock at recording time (duration will be ~0).
        # Should not be reached after the closure fix — log for diagnostics.
        started_at = now
        _LOGGER.warning(
            "MissionStore: no cached start_ts for mission — duration will be 0"
        )

    phase = mission.get("phase", "")
    error_code: int = mission.get("error", 0) or 0
    if error_code:
        result = "error"
    elif phase == "cancelled":
        result = "cancelled"
    elif nstuck_delta > 0:
        result = "stuck"
    else:
        result = "completed"

    elapsed_sec = (now - started_at).total_seconds()
    duration_min = max(0, round(elapsed_sec / 60))

    # Merge bbrun + runtimeStats — mirrors entity.py run_stats.
    # On i-series (lewis firmware) hr lives in runtimeStats, not bbrun.
    bbrun = reported.get("bbrun", {})
    runtime = reported.get("runtimeStats", {})
    bbrun_hr = bbrun.get("hr") or runtime.get("hr") or 0

    record: dict[str, Any] = {
        "id": f"m_{int(started_at.timestamp())}",
        "started_at": started_at.isoformat(),
        "ended_at": now.isoformat(),
        "duration_min": duration_min,
        "area_sqft": mission.get("sqft"),   # None for 600-series — correct
        "result": result,
        "initiator": mission.get("initiator", "none"),
        "zones": zones,
        "error_code": error_code if error_code else None,
        "bbrun_hr": bbrun_hr,
    }

    await data.mission_store.async_append(record)
    await data.mission_store.async_save(hass, entry.entry_id)

    # Update L3 runtime error state.
    # Only update on error/stuck — do NOT clear on completed so the last
    # error remains visible until the next error occurs.
    if result in ("error", "stuck"):
        data.last_error_code = error_code if error_code else None
        data.last_error_at   = now.isoformat()
        data.last_error_zone = zones[0] if zones else None

    _LOGGER.debug(
        "MissionStore: recorded %s result=%s duration=%dmin zones=%s",
        record["id"], result, duration_min, zones,
    )


# ── Callback factories ────────────────────────────────────────────────────────

def make_mission_callback(
    hass: Any,
    entry: RoombaConfigEntry,
) -> Any:
    """Return an MQTT message callback that tracks mission lifecycle.

    Returned callable is suitable for roomba.register_on_message_callback().
    Closure holds mutable state for phase tracking across messages.
    """
    last_phase: str = ""
    current_mission_zones: list[str] = []
    mission_start_ts: int = 0
    nstuck_at_start: int = 0

    def _on_mission_message(json_data: dict[str, Any]) -> None:
        nonlocal last_phase, current_mission_zones, mission_start_ts, nstuck_at_start

        reported = json_data.get("state", {}).get("reported", {})
        if "cleanMissionStatus" not in reported:
            return
        mission = reported["cleanMissionStatus"]
        phase = mission.get("phase", "")

        # Capture zone names and start metadata at mission START.
        # lastCommand.regions is fresh at start — may be overwritten by end.
        # mssnStrtTm is cached here because 980/900-series firmware resets it
        # to 0 in the mission-end MQTT message.
        if phase in _CLEANING_PHASES and last_phase not in _CLEANING_PHASES:
            current_mission_zones = _capture_zone_names(entry, reported)
            mission_start_ts = mission.get("mssnStrtTm") or 0
            bbrun = reported.get("bbrun", {})
            nstuck_at_start = bbrun.get("nStuck", 0)
            _LOGGER.debug(
                "MissionStore: mission started ts=%s nstuck_baseline=%d",
                mission_start_ts, nstuck_at_start,
            )

        if phase in _MISSION_END_PHASES and last_phase in _CLEANING_PHASES:
            bbrun_end = reported.get("bbrun", {})
            nstuck_delta = max(0, bbrun_end.get("nStuck", 0) - nstuck_at_start)
            asyncio.run_coroutine_threadsafe(
                async_record_mission(
                    hass,
                    entry,
                    mission,
                    reported,
                    list(current_mission_zones),
                    start_ts=mission_start_ts,
                    nstuck_delta=nstuck_delta,
                ),
                hass.loop,
            )
            current_mission_zones = []
            mission_start_ts = 0
            nstuck_at_start = 0

        last_phase = phase

    return _on_mission_message


def make_map_retrain_callback(
    hass: Any,
    cloud_coordinator: IrobotCloudCoordinator,
) -> Any:
    """Return an MQTT message callback that detects Smart Map retrains.

    Triggers an immediate cloud coordinator refresh when user_pmapv_id
    changes in the MQTT state — earlier than the 24-hour poll interval.
    """
    last_pmapv: dict[str, str] = {}  # pmap_id → last seen pmapv_id

    def _on_roomba_message(json_data: dict[str, Any]) -> None:
        reported = json_data.get("state", {}).get("reported", {})
        pmaps: list[dict] = reported.get("pmaps", [])
        changed = False
        for pmap_entry in pmaps:
            for pid, pmapv in pmap_entry.items():
                if last_pmapv.get(pid) not in (None, pmapv):
                    _LOGGER.info(
                        "Roomba+ cloud: user_pmapv_id changed for pmap %s "
                        "(%s → %s) — triggering cloud refresh",
                        pid[:12], last_pmapv[pid][:12], pmapv[:12],
                    )
                    changed = True
                last_pmapv[pid] = pmapv
        if changed:
            asyncio.run_coroutine_threadsafe(
                cloud_coordinator.async_request_refresh(), hass.loop
            )

    return _on_roomba_message
