"""iRobot Cloud API client for Roomba+.

Implements the modern Gigya → AWS Cognito authentication flow and exposes the
iRobot REST endpoints used by SMART-capable robots (i/s/j-series) and for
mission-history polling on all robots.

Auth flow:
  1. Discover deployment endpoints from disc-prod.iot.irobotapi.com
  2. Login via Gigya SSO to obtain UID + signature
  3. Exchange with iRobot /v2/login to get AWS Cognito credentials
  4. Sign all data requests with AWS SigV4

Based on reverse engineering documented in roomba_rest980 (cloudReverse.md).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import hashlib
import hmac
import json
from json.decoder import JSONDecodeError
import logging
import urllib.parse
import uuid
from datetime import UTC, datetime
from typing import Any

import aiohttp

_LOGGER = logging.getLogger(__name__)

def _discovery_url(country_code: str) -> str:
    """Return the iRobot endpoint discovery URL for the given ISO 3166-1 country code.

    iRobot splits its backend by region. Using the wrong country code results
    in /missionhistory and other endpoints returning empty data for EU accounts.
    The correct code is read from hass.config.country at coordinator startup.
    Falls back to "US" when HA has no country configured.
    """
    return f"https://disc-prod.iot.irobotapi.com/v1/discover/endpoints?country_code={country_code}"


# Backward-compatible name used by existing tests (v1.8.3+: parameterised by country_code)
DISCOVERY_URL: str = _discovery_url("US")

_USER_AGENT_APP = "iRobot/7.16.2.140449 CFNetwork/1568.100.1.2.1 Darwin/24.0.0"
_USER_AGENT_AWS = "aws-sdk-iOS/2.27.6 iOS/18.0.1 en_US"


class CloudApiError(Exception):
    """Base exception for Cloud API errors."""


class AuthenticationError(CloudApiError):
    """Authentication failed — bad credentials or rate-limited."""


# ── AWS SigV4 ─────────────────────────────────────────────────────────────────

class _AWSSignatureV4:
    """Minimal AWS Signature Version 4 implementation for iRobot API requests."""

    def __init__(self, access_key_id: str, secret_access_key: str, session_token: str) -> None:
        self._key_id = access_key_id
        self._secret = secret_access_key
        self._token = session_token

    @staticmethod
    def _hmac_sha256(key: bytes, data: str) -> bytes:
        return hmac.new(key, data.encode(), hashlib.sha256).digest()

    @staticmethod
    def _sha256_hex(data: str) -> str:
        return hashlib.sha256(data.encode()).hexdigest()

    def _signing_key(self, date_stamp: str, region: str, service: str) -> bytes:
        k = self._hmac_sha256(f"AWS4{self._secret}".encode(), date_stamp)
        k = self._hmac_sha256(k, region)
        k = self._hmac_sha256(k, service)
        return self._hmac_sha256(k, "aws4_request")

    def signed_headers(
        self,
        method: str,
        service: str,
        region: str,
        host: str,
        path: str,
        query_params: dict[str, Any] | None = None,
    ) -> dict[str, str]:
        """Return a dict of headers with AWS SigV4 Authorization included."""
        now = datetime.now(tz=UTC)
        amz_date = now.strftime("%Y%m%dT%H%M%SZ")
        date_stamp = now.strftime("%Y%m%d")

        canonical_uri = urllib.parse.quote(path, safe="/")
        qp = query_params or {}
        canonical_qs = "&".join(
            f"{urllib.parse.quote(k, safe='~')}={urllib.parse.quote(str(v), safe='~')}"
            for k in sorted(qp)
            for v in [qp[k]]
        )

        base_headers = {
            "accept": "application/json",
            "content-type": "application/json",
            "host": host,
            "user-agent": _USER_AGENT_AWS,
            "x-amz-date": amz_date,
        }
        sorted_keys = sorted(base_headers)
        canonical_headers = "".join(f"{k}:{base_headers[k]}\n" for k in sorted_keys)
        signed_hdrs = ";".join(sorted_keys)

        payload_hash = self._sha256_hex("")
        canonical_req = "\n".join([
            method.upper(), canonical_uri, canonical_qs,
            canonical_headers, signed_hdrs, payload_hash,
        ])

        algorithm = "AWS4-HMAC-SHA256"
        scope = f"{date_stamp}/{region}/{service}/aws4_request"
        string_to_sign = "\n".join([
            algorithm, amz_date, scope, self._sha256_hex(canonical_req),
        ])

        sig = hmac.new(
            self._signing_key(date_stamp, region, service),
            string_to_sign.encode(),
            hashlib.sha256,
        ).hexdigest()

        authorization = (
            f"{algorithm} Credential={self._key_id}/{scope}, "
            f"SignedHeaders={signed_hdrs}, Signature={sig}"
        )

        return {
            **base_headers,
            "Authorization": authorization,
            "x-amz-security-token": self._token,
        }


# ── Cloud API client ──────────────────────────────────────────────────────────

class IrobotCloudApi:
    """iRobot Cloud API client.

    Authenticates once per session and exposes the data endpoints used by
    Roomba+. All network calls are async (aiohttp).

    Usage:
        api = IrobotCloudApi(username, password, session)
        await api.authenticate()
        pmaps = await api.get_pmaps(blid)
    """

    def __init__(
        self,
        username: str,
        password: str,
        session: aiohttp.ClientSession,
        country_code: str = "US",
    ) -> None:
        self._username = username
        self._password = password
        self._session = session
        self._country_code = country_code

        self._app_id = str(uuid.uuid4())
        self._device_id = str(uuid.uuid4())

        # Filled by authenticate()
        self._deployment: dict[str, Any] = {}
        self._credentials: dict[str, Any] = {}
        self.robots: dict[str, Any] = {}   # blid → robot_info

    # ── Auth ──────────────────────────────────────────────────────────────────

    async def authenticate(self) -> None:
        """Run the full Gigya → iRobot auth flow. Stores credentials in-place."""
        endpoints = await self._discover()
        gigya_key = endpoints["gigya"]["api_key"]
        uid, sig, ts = await self._login_gigya(endpoints["gigya"], gigya_key)
        await self._login_irobot(uid, sig, ts)
        _LOGGER.info("iRobot cloud: authenticated, %d robot(s) found", len(self.robots))

    async def _discover(self) -> dict[str, Any]:
        async with self._session.get(_discovery_url(self._country_code)) as resp:
            if resp.status != 200:
                raise CloudApiError(f"Endpoint discovery failed: {resp.status}")
            data = await resp.json()
        self._deployment = data["deployments"][data["current_deployment"]]
        return data

    async def _login_gigya(
        self, gigya_cfg: dict, api_key: str
    ) -> tuple[str, str, str]:
        base = f"https://accounts.{gigya_cfg['datacenter_domain']}/accounts."
        payload = {
            "loginMode": "standard",
            "loginID": self._username,
            "password": self._password,
            "include": "profile,data,emails,subscriptions,preferences,",
            "includeUserInfo": "true",
            "targetEnv": "mobile",
            "source": "showScreenSet",
            "sdk": "ios_swift_1.3.0",
            "sessionExpiration": "-2",
            "apikey": api_key,
        }
        headers = {
            "Content-Type": "application/x-www-form-urlencoded",
            "User-Agent": _USER_AGENT_APP,
        }
        async with self._session.post(
            f"{base}login",
            headers=headers,
            data=urllib.parse.urlencode(payload),
        ) as resp:
            text = await resp.text()

        try:
            result = json.loads(text)
        except JSONDecodeError as exc:
            raise AuthenticationError(f"Invalid Gigya response: {text[:200]}") from exc

        if result.get("errorCode", 0) != 0:
            raise AuthenticationError(f"Gigya login failed: {result.get('errorMessage', result)}")

        for key in ("UID", "UIDSignature", "signatureTimestamp"):
            if key not in result:
                raise AuthenticationError(f"Missing '{key}' in Gigya response")

        return result["UID"], result["UIDSignature"], result["signatureTimestamp"]

    async def _login_irobot(self, uid: str, uid_sig: str, sig_ts: str) -> None:
        payload = {
            "app_id": f"IOS-{self._app_id}",
            "app_info": {
                "device_id": f"IOS-{self._device_id}",
                "device_name": "iPhone",
                "language": "en_US",
                "version": "7.16.2",
            },
            "assume_robot_ownership": "0",
            "authorizer_params": {"devices_per_token": 5},
            "gigya": {"signature": uid_sig, "timestamp": sig_ts, "uid": uid},
            "multiple_authorizer_token_support": True,
            "push_info": {
                "platform": "APNS",
                "push_token": "eb6ce9172e5fde9fe4c9a2a945b35709f73fb8014eb7449d944c6c89eeb472fb",
                "supported_push_types": ["cr", "cse", "bf", "ae", "pm", "te", "dt"],
            },
            "skip_ownership_check": "0",
        }
        async with self._session.post(
            f"{self._deployment['httpBase']}/v2/login",
            headers={"Content-Type": "application/json"},
            json=payload,
        ) as resp:
            text = await resp.text()

        try:
            result = json.loads(text)
        except JSONDecodeError as exc:
            raise AuthenticationError(f"Invalid iRobot login response: {text[:200]}") from exc

        if result.get("errorCode"):
            msg = result.get("errorMessage") or str(result)
            if "mqtt slot" in msg.lower():
                msg = (
                    "Cloud auth rate-limited. Close the iRobot app and try again. "
                    f"({msg})"
                )
            raise AuthenticationError(msg)

        if "credentials" not in result:
            raise AuthenticationError(f"No credentials in iRobot login response: {result}")

        self._credentials = result["credentials"]
        self.robots = result.get("robots", {})

    # ── Authenticated requests ─────────────────────────────────────────────────

    async def _aws_get(
        self, url: str, params: dict[str, Any] | None = None, *, _retry: bool = True
    ) -> Any:
        """GET url with AWS SigV4 signing. Reauthenticates once on 403."""
        if not self._credentials:
            raise AuthenticationError("Not authenticated — call authenticate() first")

        region = self._credentials["CognitoId"].split(":")[0]
        parsed = urllib.parse.urlparse(url)
        signer = _AWSSignatureV4(
            self._credentials["AccessKeyId"],
            self._credentials["SecretKey"],
            self._credentials["SessionToken"],
        )
        headers = signer.signed_headers(
            method="GET",
            service="execute-api",
            region=region,
            host=parsed.netloc,
            path=parsed.path,
            query_params=params or {},
        )
        final_url = url
        if params:
            final_url = f"{url}?{urllib.parse.urlencode(params)}"

        async with self._session.get(final_url, headers=headers) as resp:
            if resp.status == 403 and _retry:
                _LOGGER.debug("iRobot cloud: 403 — reauthenticating")
                await self.authenticate()
                return await self._aws_get(url, params, _retry=False)
            if resp.status != 200:
                raise CloudApiError(f"Cloud request failed ({resp.status}): {url}")
            return await resp.json()

    # ── Public data endpoints ─────────────────────────────────────────────────

    async def get_pmaps(self, blid: str) -> list[dict[str, Any]]:
        """Return persistent map list for a robot. Each entry includes pmap_id,
        active_pmapv_id, and active_pmapv_details (regions, zones, UMF header).
        """
        url = f"{self._deployment['httpBaseAuth']}/v1/{blid}/pmaps"
        result = await self._aws_get(url, {"visible": "true", "activeDetails": "2"})
        return result if isinstance(result, list) else []

    async def get_pmap_umf(
        self, blid: str, pmap_id: str, version_id: str
    ) -> dict[str, Any]:
        """Return the Unified Map Format data for a specific pmap version."""
        url = (
            f"{self._deployment['httpBaseAuth']}/v1/{blid}"
            f"/pmaps/{pmap_id}/versions/{version_id}/umf"
        )
        return await self._aws_get(url, {"activeDetails": "2"})

    async def get_mission_history(self, blid: str) -> dict[str, Any]:
        """Return mission history (lifetime stats) for a robot."""
        url = f"{self._deployment['httpBaseAuth']}/v1/{blid}/missionhistory"
        return await self._aws_get(url, {
            "app_id": f"IOS-{self._app_id}",
            "filterType": "omit_quickly_canceled_not_scheduled",
            "supportedDoneCodes": "dndEnd,returnHomeEnd",
        })

    async def get_favorites(self) -> list[dict[str, Any]]:
        """Return user-defined favorite cleaning routines."""
        url = f"{self._deployment['httpBaseAuth']}/v1/user/favorites"
        result = await self._aws_get(url)
        return result if isinstance(result, list) else result.get("favorites", [])
