"""Cloud data coordinator for Roomba+.

Polls the iRobot cloud API once per HA session (at setup) and again whenever
a map retrain is detected via MQTT (user_pmapv_id change). Between those
events the cloud data is stable — pmaps only change when the user physically
retrains or edits room boundaries.

The coordinator is only created for MapCapability.SMART robots AND when the
user has supplied iRobot cloud credentials. All existing local-MQTT behaviour
is completely unaffected when this coordinator is absent.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
from datetime import timedelta
from typing import Any

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.exceptions import ConfigEntryAuthFailed
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from homeassistant.helpers.update_coordinator import DataUpdateCoordinator, UpdateFailed

from .cloud_api import AuthenticationError, CloudApiError, IrobotCloudApi

_LOGGER = logging.getLogger(__name__)

# Cloud map data changes only on map retrain — poll once per day as a
# backstop; real refresh is triggered by user_pmapv_id MQTT change.
_CLOUD_POLL_INTERVAL = timedelta(hours=24)



def classify_mission_result(record: dict) -> str:
    """Classify a raw /missionhistory record into a canonical result string.

    Uses the v2.0 classification scheme, which is more granular than the
    v1.9 MQTT-based scheme in callbacks.py:

      "completed"          — done="done"
      "cancelled_by_user"  — done_raw="usrEnd" (user pressed stop in the app)
      "cancelled"          — done="cncl" but not user-initiated
      "error_{code}"       — done="stuck" + pauseId>0, e.g. "error_17"
      "stuck"              — done="stuck" + pauseId=0 (no specific code)
      "unknown"            — unrecognised done value, logged for analysis

    Priority: done_raw wins over done for user-cancellation detection because
    the iRobot cloud normalises "usrEnd" → "cncl" in the done field, losing
    the user-intent signal. pauseId is the authoritative error code from the
    cloud — more reliable than cleanMissionStatus.error from MQTT, which
    sometimes never arrives on 900-series firmware.

    Args:
        record: A single raw record dict from /missionhistory.

    Returns:
        Canonical result string for use in sensors and REST API.
    """
    done: str = record.get("done", "") or ""
    done_raw: str = record.get("done_raw", "") or ""
    pause_id: int = int(record.get("pauseId", 0) or 0)

    if done == "done":
        return "completed"

    if done_raw == "usrEnd":
        return "cancelled_by_user"

    if done in ("cncl",):
        return "cancelled"

    if done == "stuck":
        if pause_id > 0:
            return f"error_{pause_id}"
        return "stuck"

    # Known done values confirmed from field logs (June 2026, Roomba 980 v2.4.17):
    if done == "ok":
        return "completed"

    if done == "full":
        return "cancelled"

    if done == "bat":
        return "error_battery"

    if done == "schErr":
        if pause_id > 0:
            return f"error_{pause_id}"
        return "cancelled"

    if done:
        import logging
        logging.getLogger(__name__).debug(
            "classify_mission_result: unknown done=%r done_raw=%r pauseId=%d — "
            "logging for further analysis",
            done, done_raw, pause_id,
        )
    return "unknown"


def _normalize_mission_history(raw: dict) -> dict:
    """Normalize a raw /missionhistory record into a consistent shape.

    The iRobot cloud /missionhistory endpoint (confirmed from field logs) returns
    a list of individual mission records. Each record uses iRobot-internal field
    names that differ from the local MQTT state:

      durationM  — mission duration in minutes (cleaning + recharge time)
      done       — True if mission completed successfully
      chrgs      — number of mid-mission recharges
      chrgM      — minutes spent recharging during this mission
      dirt       — dirt detection events (scrub count)
      sqft       — area cleaned this mission in sq ft (may be present)

    This function is called with the FIRST record from the list. For aggregate
    lifetime stats, the coordinator passes the full list to _aggregate_history()
    and stores those results instead.

    This single-record normalizer is kept for backward compatibility and for
    cases where the API may return a summary dict rather than a list.

    Canonical output shape:
      {
        "runtimeStats": {"sqft": int, "hr": int, "min": int},
        "bbmssn":       {"nMssn": int},
      }
    """
    if not raw:
        return {}

    runtime = raw.get("runtimeStats") or {}
    bbrun   = raw.get("bbrun") or {}
    bbmssn  = raw.get("bbmssn") or {}

    # Try legacy/accumulator paths first (some account types return summary dict)
    sqft = runtime.get("sqft") or bbrun.get("sqft")
    hr   = runtime.get("hr")   or bbrun.get("hr")
    mn   = runtime.get("min")  or bbrun.get("min")
    n_mssn = bbmssn.get("nMssn") or raw.get("nMssn")

    # iRobot individual-record format: durationM in minutes
    if hr is None and mn is None:
        duration_m = raw.get("durationM") or raw.get("doneM") or 0
        if duration_m:
            hr = int(duration_m) // 60
            mn = int(duration_m) % 60

    # sqft from individual record — only if no better source found
    # NOTE: raw["sqft"] in individual records = THIS MISSION only, not lifetime.
    # We deliberately do NOT use it here to avoid showing per-mission sqft as
    # lifetime total. The aggregate path handles lifetime correctly.
    if sqft is None:
        sqft = raw.get("sqft")  # per-mission fallback, marked in attributes

    result: dict = {}
    if sqft is not None or hr is not None or mn is not None:
        result["runtimeStats"] = {}
        if sqft is not None:
            result["runtimeStats"]["sqft"] = int(sqft)
        if hr is not None:
            result["runtimeStats"]["hr"] = int(hr)
        if mn is not None:
            result["runtimeStats"]["min"] = int(mn)
    if n_mssn is not None:
        result["bbmssn"] = {"nMssn": int(n_mssn)}

    return result


def _aggregate_history(records: list) -> dict:
    """Aggregate a list of individual mission records into totals.

    Confirmed field names from field logs (980 firmware v2.4.17-138):
      nMssn     — LIFETIME mission count (same value in every record)
      durationM — this mission duration in minutes (run + recharge time)
      runM      — actual cleaning time in minutes (excl. recharge)
      chrgM     — time spent recharging mid-mission in minutes
      chrgs     — number of mid-mission recharges
      done      — mission result string: "done" / "stuck" / other
      pauseId   — error code when done != "done" (17 = cannot find home)
      sqft      — area cleaned this mission in sq ft
      evacs     — bin evacuation count this mission
      initiator — who started the mission

    nMssn strategy: every record contains the LIFETIME mission counter at
    the time of that mission. We read it from the first record to get the
    most recent lifetime total, NOT len(records) which is just the API
    window size (~30 days).

    For running time and area we SUM across all records — these represent
    the total for the API window (not lifetime).
    """
    if not records:
        return {}

    total_min  = 0
    total_sqft = 0
    has_sqft   = False

    # nMssn is the lifetime counter embedded in each record.
    # Use the first valid record's value for the current lifetime total.
    n_mssn_lifetime = None
    for r in records:
        if isinstance(r, dict) and r.get("nMssn") is not None:
            n_mssn_lifetime = int(r["nMssn"])
            break

    # Fall back to record count if nMssn not found (older firmware)
    n_mssn = n_mssn_lifetime if n_mssn_lifetime is not None else len(records)

    for r in records:
        if not isinstance(r, dict):
            continue
        # Use runM (actual cleaning time) preferred over durationM (incl. recharge)
        # Fall back chain: runM -> durationM -> doneM
        duration_m = r.get("runM") or r.get("durationM") or r.get("doneM") or 0
        total_min += int(duration_m)
        sqft = r.get("sqft")
        if sqft is not None:
            total_sqft += int(sqft)
            has_sqft = True

    result: dict = {
        "bbmssn": {"nMssn": n_mssn},
    }
    if total_min > 0:
        result["runtimeStats"] = {
            "hr":  total_min // 60,
            "min": total_min % 60,
        }
        if has_sqft:
            result["runtimeStats"]["sqft"] = total_sqft

    return result


class IrobotCloudCoordinator(DataUpdateCoordinator[dict[str, Any]]):
    """Coordinator for iRobot cloud data (pmaps, mission history, favorites).

    data structure after a successful update:
    {
        "pmaps": [...],          # list of pmap dicts from /pmaps
        "mission_history": {...},# from /missionhistory
        "favorites": [...],      # from /user/favorites
    }
    All keys are always present; they default to empty list/dict on error.

    For EPHEMERAL robots (980/900-series): pmaps and favorites are always
    empty lists — only missionhistory is fetched. For SMART robots all
    three endpoints are fetched.
    """

    def __init__(
        self,
        hass: HomeAssistant,
        config_entry: ConfigEntry,
        blid: str,
        username: str,
        password: str,
        has_pmaps: bool = False,
    ) -> None:
        super().__init__(
            hass,
            _LOGGER,
            name=f"iRobot cloud ({blid})",
            config_entry=config_entry,
            update_interval=_CLOUD_POLL_INTERVAL,
        )
        self.blid = blid
        self._has_pmaps = has_pmaps
        country_code = (hass.config.country or "US").upper()
        self.api = IrobotCloudApi(
            username=username,
            password=password,
            session=async_get_clientsession(hass),
            country_code=country_code,
        )
        _LOGGER.debug(
            "iRobot cloud: using country_code=%s, has_pmaps=%s for %s",
            country_code, has_pmaps, blid,
        )

    async def _async_setup(self) -> None:
        """Authenticate once when the coordinator is first started."""
        try:
            await self.api.authenticate()
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud credentials are invalid: {exc}"
            ) from exc
        except CloudApiError as exc:
            # Transient — let HA retry via ConfigEntryNotReady pathway
            raise UpdateFailed(f"iRobot cloud setup failed: {exc}") from exc

    async def _async_update_data(self) -> dict[str, Any]:
        """Fetch current cloud data for this robot."""
        result: dict[str, Any] = {
            "pmaps": [],
            "mission_history": {},
            "mission_history_raw": [],   # v2.0: full per-mission record list
            "favorites": [],
        }
        try:
            async with asyncio.timeout(30):
                # pmaps and favorites require cap.pmaps — SMART robots only.
                # missionhistory is account-level and available for all robots.
                if self._has_pmaps:
                    result["pmaps"] = await self.api.get_pmaps(self.blid)
                    result["favorites"] = await self.api.get_favorites()
                raw_history = await self.api.get_mission_history(self.blid)
        except AuthenticationError as exc:
            raise ConfigEntryAuthFailed(
                f"iRobot cloud authentication failed: {exc}"
            ) from exc
        except CloudApiError as exc:
            raise UpdateFailed(f"iRobot cloud update failed: {exc}") from exc

        # The /missionhistory endpoint returns a list of records.
        # Structure varies by firmware/region:
        #   - Some accounts: list where [0] is a lifetime accumulator dict
        #     with runtimeStats.sqft/hr/min and bbmssn.nMssn
        #   - Some accounts: list of individual mission records where lifetime
        #     totals are in bbrun.sqft/hr and bbmssn.nMssn
        #   - Some firmware: a single dict directly
        # We log the raw structure at DEBUG level so users can report issues.
        if isinstance(raw_history, list) and raw_history:
            _first  = raw_history[0] if isinstance(raw_history[0], dict) else {}
            _second = (
                raw_history[1] if len(raw_history) > 1 and isinstance(raw_history[1], dict)
                else {}
            )
            # Collect all unique keys across all records to detect
            # fields that only appear on certain result types
            _all_keys: set = set()
            for _r in raw_history:
                if isinstance(_r, dict):
                    _all_keys.update(_r.keys())
            _LOGGER.debug(
                "iRobot cloud: raw_history len=%d "
                "all_keys=%s "
                "first_record=%s "
                "second_record=%s "
                "for %s",
                len(raw_history),
                sorted(_all_keys),
                _first,    # full first record (all fields)
                _second,   # full second record (may differ from first)
                self.blid,
            )
        elif isinstance(raw_history, dict):
            _first = raw_history
            _LOGGER.debug(
                "iRobot cloud: raw_history dict_record=%s for %s",
                raw_history, self.blid,
            )
        else:
            _first = {}
            _LOGGER.debug(
                "iRobot cloud: raw_history unexpected type=%s for %s",
                type(raw_history).__name__, self.blid,
            )

        if isinstance(raw_history, list):
            if raw_history:
                # Store raw per-mission records for v2.0 sensors and REST API.
                # Each record preserves all 28 confirmed fields from the API
                # (startTime, timestamp, sqft, done, done_raw, pauseId, wlBars, etc.)
                # A pre-computed "classified_result" field is added so consumers
                # don't need to call classify_mission_result() themselves.
                result["mission_history_raw"] = [
                    {**r, "classified_result": classify_mission_result(r)}
                    for r in raw_history
                    if isinstance(r, dict)
                ]
                # Aggregate ALL records for lifetime totals.
                result["mission_history"] = _aggregate_history(raw_history)
                _LOGGER.debug(
                    "iRobot cloud: aggregated %d mission records -> "
                    "nMssn=%s hr=%s sqft=%s for %s",
                    len(raw_history),
                    result["mission_history"].get("bbmssn", {}).get("nMssn"),
                    result["mission_history"].get("runtimeStats", {}).get("hr"),
                    result["mission_history"].get("runtimeStats", {}).get("sqft"),
                    self.blid,
                )
            else:
                result["mission_history"] = {}
                result["mission_history_raw"] = []
        elif isinstance(raw_history, dict):
            # Some account types may return a summary dict directly.
            result["mission_history"] = _normalize_mission_history(raw_history)
        else:
            result["mission_history"] = {}
            _LOGGER.warning(
                "iRobot cloud: unexpected mission_history type %s for %s",
                type(raw_history).__name__, self.blid,
            )

        _LOGGER.debug(
            "iRobot cloud: fetched %d pmap(s), %d favorite(s) for %s (has_pmaps=%s)",
            len(result["pmaps"]),
            len(result["favorites"]),
            self.blid,
            self._has_pmaps,
        )
        return result

    # ── Helpers used by platforms ─────────────────────────────────────────────

    @property
    def raw_records(self) -> list[dict[str, Any]]:
        """Return the raw per-mission records from the last /missionhistory fetch.

        Records are ordered newest-first (as returned by the API).
        Each record contains all confirmed fields: startTime, timestamp, sqft,
        done, done_raw, pauseId, wlBars, runM, chrgs, evacs, dirt, initiator, etc.

        Returns an empty list when no cloud data is available or the API
        returned an empty/non-list response.
        """
        if not self.data:
            return []
        return self.data.get("mission_history_raw", [])

    @property
    def active_pmap_id(self) -> str | None:
        """Return the pmap_id of the first active pmap, or None."""
        if not self.data:
            return None
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            pid = pmapv.get("pmap_id")
            if pid:
                return pid
        return None

    @property
    def regions(self) -> list[dict[str, Any]]:
        """Return regions from the ACTIVE pmap only.

        Deliberately ignores disabled/old maps to prevent room-name collisions
        when multiple Smart Maps exist in the same iRobot account. A user with
        an old disabled map and a current map that share room names would
        otherwise get silent wrong-map cleans (Case 1) or rooms_different_floors
        errors (Case 2) from _resolve_rooms.
        """
        if not self.data:
            return []
        active_id = self.active_pmap_id
        if not active_id:
            return []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            if pmapv.get("pmap_id") != active_id:
                continue  # skip disabled / inactive maps
            return [
                {
                    "id": region.get("id", ""),
                    "name": region.get("name", ""),
                    "region_type": region.get("region_type", "default"),
                    "pmap_id": active_id,
                }
                for region in details.get("regions", [])
            ]
        return []

    @property
    def zones(self) -> list[dict[str, Any]]:
        """Return custom zones from the ACTIVE pmap only.

        Same active-map filter as regions — prevents stale zone data from
        disabled maps contaminating zone_data lookups.
        """
        if not self.data:
            return []
        active_id = self.active_pmap_id
        if not active_id:
            return []
        for pmap in self.data.get("pmaps", []):
            details = pmap.get("active_pmapv_details", {})
            pmapv = details.get("active_pmapv", {})
            if pmapv.get("pmap_id") != active_id:
                continue
            return [
                {
                    "id": zone.get("id", ""),
                    "name": zone.get("name", ""),
                    "zone_type": zone.get("zone_type", "default"),
                    "pmap_id": active_id,
                }
                for zone in details.get("zones", [])
            ]
        return []
