"""Mission Store for Roomba+ — append-only mission history log.

Persists up to 365 mission records per robot, keyed by config entry ID.
Provides query, aggregation, and window-analysis methods consumed by
L1 sensors, L3 error intelligence, L6 presence analytics, and the
REST API view.

No HA dependencies at import time — fully unit-testable without stubs.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store
from homeassistant.util import dt as dt_util

_LOGGER = logging.getLogger(__name__)

STORAGE_KEY_PREFIX = "roomba_plus_missions"
STORAGE_VERSION = 1
MAX_RECORDS = 365


@dataclass(frozen=True)
class DaySummary:
    """Aggregated mission stats for a single calendar day."""

    date: date
    total: int
    completed: int
    stuck: int
    area_sqft: float | None   # sum for day; None if 600-series
    result: str               # dominant: "error" > "stuck" > "completed" > "cancelled" > "none"


@dataclass(frozen=True)
class MissionWindow:
    """A gap between two consecutive missions — potential all-away window."""

    started_at: datetime
    ended_at: datetime
    duration_min: int
    resulted_in_clean: bool   # True if a completed mission started within this window


class MissionStore:
    """Append-only mission log — max 365 records FIFO.

    Lifecycle (must be respected by callers):
      - Instantiate in async_setup_entry.
      - Call async_load() immediately after instantiation.
      - Store in entry.runtime_data.mission_store.
      - No active listeners — no cancel/unload cleanup required.
    """

    def __init__(self) -> None:
        self._records: list[dict[str, Any]] = []

    # ── Persistence ───────────────────────────────────────────────────────────

    async def async_load(self, hass: HomeAssistant, entry_id: str) -> None:
        """Load persisted records from hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        data: dict | None = await store.async_load()
        if not data:
            _LOGGER.debug("MissionStore: no persisted data for %s", entry_id)
            return
        try:
            self._records = list(data.get("records", []))
            _LOGGER.debug("MissionStore: loaded %d record(s) for %s", len(self._records), entry_id)
        except (TypeError, ValueError) as exc:
            _LOGGER.warning("MissionStore: failed to load — %s; starting empty", exc)
            self._records = []

    async def async_save(self, hass: HomeAssistant, entry_id: str) -> None:
        """Persist current records to hass.storage."""
        store = Store(hass, STORAGE_VERSION, f"{STORAGE_KEY_PREFIX}_{entry_id}")
        await store.async_save({"records": self._records})

    # ── Write ─────────────────────────────────────────────────────────────────

    async def async_append(self, record: dict[str, Any]) -> None:
        """Append a record and trim to MAX_RECORDS FIFO."""
        self._records.append(record)
        if len(self._records) > MAX_RECORDS:
            self._records = self._records[-MAX_RECORDS:]

    # ── Read ──────────────────────────────────────────────────────────────────

    def latest(self) -> dict[str, Any] | None:
        """Return the most recent record, or None."""
        return self._records[-1] if self._records else None

    def query(self, days: int, result: str | None = None) -> list[dict[str, Any]]:
        """Return records from the last `days` days, optionally filtered by result.

        Records are returned sorted ascending by started_at.
        """
        cutoff = dt_util.now() - timedelta(days=days)
        out = []
        for r in self._records:
            started = dt_util.parse_datetime(r.get("started_at", ""))
            if started is None:
                continue
            # Make started timezone-aware for comparison if needed
            if started.tzinfo is None:
                started = started.replace(tzinfo=timezone.utc)
            if started < cutoff:
                continue
            if result is not None and r.get("result") != result:
                continue
            out.append(r)
        return sorted(out, key=lambda r: r.get("started_at", ""))

    def query_by_day(self, days: int) -> dict[date, DaySummary]:
        """Group query(days) results by local calendar date.

        Returns a dict keyed by date. Days with no missions are omitted.
        """
        from collections import defaultdict
        buckets: dict[date, list[dict]] = defaultdict(list)
        for r in self.query(days):
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt:
                buckets[dt_util.as_local(dt).date()].append(r)

        summaries: dict[date, DaySummary] = {}
        for day, records in buckets.items():
            total = len(records)
            completed = sum(1 for r in records if r.get("result") == "completed")
            stuck = sum(1 for r in records if r.get("result") == "stuck")
            areas = [r["area_sqft"] for r in records if r.get("area_sqft") is not None]
            area_sqft: float | None = float(sum(areas)) if areas else None
            # Dominant result: error > stuck > completed > cancelled > none
            results = {r.get("result") for r in records}
            dominant = (
                "error" if "error" in results else
                "stuck" if "stuck" in results else
                "completed" if "completed" in results else
                "cancelled" if "cancelled" in results else
                "none"
            )
            summaries[day] = DaySummary(
                date=day,
                total=total,
                completed=completed,
                stuck=stuck,
                area_sqft=area_sqft,
                result=dominant,
            )
        return summaries

    def presence_windows(self, days: int) -> list[MissionWindow]:
        """Return gaps between missions as potential 'all-away' windows.

        Each window spans from the end of one mission to the start of the next.
        resulted_in_clean=True when a completed mission started within the window.
        Used by L6 analytics sensors.
        """
        records = self.query(days)
        if len(records) < 2:
            return []

        windows: list[MissionWindow] = []
        completed_starts: set[str] = {
            r["started_at"] for r in records if r.get("result") == "completed"
        }

        for i in range(len(records) - 1):
            prev_end_str = records[i].get("ended_at", "")
            next_start_str = records[i + 1].get("started_at", "")
            prev_end = dt_util.parse_datetime(prev_end_str)
            next_start = dt_util.parse_datetime(next_start_str)
            if prev_end is None or next_start is None:
                continue
            # Make timezone-aware if needed
            if prev_end.tzinfo is None:
                prev_end = prev_end.replace(tzinfo=timezone.utc)
            if next_start.tzinfo is None:
                next_start = next_start.replace(tzinfo=timezone.utc)
            if next_start <= prev_end:
                continue
            duration_min = int((next_start - prev_end).total_seconds() / 60)
            resulted = next_start_str in completed_starts
            windows.append(MissionWindow(
                started_at=prev_end,
                ended_at=next_start,
                duration_min=duration_min,
                resulted_in_clean=resulted,
            ))
        return windows

    def clean_streak(self) -> int:
        """Return consecutive days ending today with at least one completed mission."""
        today = dt_util.now().date()
        completed_dates: set[date] = set()
        for r in self._records:
            if r.get("result") == "completed":
                dt = dt_util.parse_datetime(r.get("started_at", ""))
                if dt:
                    completed_dates.add(dt_util.as_local(dt).date())
        streak = 0
        day = today
        while day in completed_dates:
            streak += 1
            day -= timedelta(days=1)
        return streak

    def wear_data(self, days: int) -> list[dict[str, Any]]:
        """Return daily bbrun.hr snapshots for the last `days` days.

        Returns one entry per calendar day — the highest recorded bbrun_hr
        value for that day — sorted ascending by date. Used by L4 wear
        intelligence to compute daily wear rates without needing consecutive-
        record arithmetic in the sensor layer.

        Returns an empty list when fewer than 2 days of data exist (not enough
        to compute a meaningful rate).
        """
        buckets: dict[date, int] = {}
        for r in self.query(days):
            dt = dt_util.parse_datetime(r.get("started_at", ""))
            if dt and r.get("bbrun_hr") is not None:
                day = dt_util.as_local(dt).date()
                if day not in buckets or r["bbrun_hr"] > buckets[day]:
                    buckets[day] = r["bbrun_hr"]
        return sorted(
            [{"date": d.isoformat(), "bbrun_hr": hr} for d, hr in buckets.items()],
            key=lambda x: x["date"],
        )

    def wear_rate_since_reset(
        self,
        reset_hr: int,
        reset_at: str | None,
        current_hr: int,
    ) -> float | None:
        """Return average bbrun hours consumed per day since the last part reset.

        Returns None when:
        - reset_at is unknown (reset never recorded or store was empty)
        - current_hr has not advanced beyond reset_hr (robot not yet used)
        - fewer than 3 days have elapsed since reset (insufficient baseline)
        - reset_at cannot be parsed

        Never returns a negative value.
        """
        if reset_at is None or current_hr <= reset_hr:
            return None
        try:
            reset_dt = dt_util.parse_datetime(reset_at)
        except (ValueError, TypeError):
            return None
        if reset_dt is None:
            return None
        if reset_dt.tzinfo is None:
            reset_dt = reset_dt.replace(tzinfo=timezone.utc)
        days_elapsed = (dt_util.utcnow() - reset_dt).total_seconds() / 86400
        if days_elapsed < 3:
            return None
        rate = (current_hr - reset_hr) / days_elapsed
        return round(max(0.0, rate), 2)

    def backfill_from_cloud(
        self,
        cloud_records: list[dict],
        tolerance_sec: int = 120,
    ) -> int:
        """Correct local MissionStore records using cloud /missionhistory timestamps.

        The 980/900-series firmware resets mssnStrtTm to 0 in the mission-end
        MQTT message. When callbacks.py cannot capture a valid start timestamp,
        started_at falls back to wall-clock at recording time, making
        duration_min ≈ 0 and the record id incorrect.

        Matches each local record against cloud records by end timestamp
        (±tolerance_sec), then corrects:
          - started_at  — from cloud startTime
          - ended_at    — from cloud timestamp
          - duration_min — recomputed from corrected timestamps
          - id          — regenerated from corrected started_at
          - area_sqft   — from cloud sqft when local value is None

        Matching uses ended_at (local) vs timestamp (cloud) because ended_at
        is always reliably recorded at wall-clock time.

        Args:
            cloud_records: raw cloud records, newest-first from API.
            tolerance_sec: max seconds between local ended_at and cloud
                           timestamp to count as the same mission. Default 120 s
                           covers MQTT delivery lag and clock skew.

        Returns:
            Number of records corrected.
        """
        if not cloud_records or not self._records:
            return 0

        # Build index of cloud records keyed by end timestamp for O(1) lookup.
        cloud_by_end: dict[int, dict] = {}
        for cr in cloud_records:
            ts = cr.get("timestamp")
            if ts is not None:
                cloud_by_end.setdefault(int(ts), cr)

        corrected = 0
        for local in self._records:
            ended_str = local.get("ended_at", "")
            if not ended_str:
                continue
            try:
                ended_dt = datetime.fromisoformat(ended_str)
            except (ValueError, TypeError):
                continue
            if ended_dt.tzinfo is None:
                ended_dt = ended_dt.replace(tzinfo=timezone.utc)
            local_end_ts = int(ended_dt.timestamp())

            # Find nearest cloud record within tolerance
            best_cr: dict | None = None
            best_delta = tolerance_sec + 1
            for cloud_ts, cr in cloud_by_end.items():
                delta = abs(cloud_ts - local_end_ts)
                if delta <= tolerance_sec and delta < best_delta:
                    best_delta = delta
                    best_cr = cr

            if best_cr is None:
                continue

            cloud_start = best_cr.get("startTime")
            cloud_end   = best_cr.get("timestamp")
            if not cloud_start or not cloud_end:
                continue

            new_started = datetime.fromtimestamp(
                int(cloud_start), tz=timezone.utc
            )
            new_ended = datetime.fromtimestamp(
                int(cloud_end), tz=timezone.utc
            )

            # Only correct if timestamps differ meaningfully (>5 min)
            old_started_str = local.get("started_at", "")
            try:
                old_started = datetime.fromisoformat(old_started_str)
                if old_started.tzinfo is None:
                    old_started = old_started.replace(tzinfo=timezone.utc)
                delta_start = abs((new_started - old_started).total_seconds())
            except (ValueError, TypeError):
                delta_start = float("inf")

            if delta_start < 300:
                continue

            new_duration = max(0, round(
                (new_ended - new_started).total_seconds() / 60
            ))
            new_id = f"m_{int(new_started.timestamp())}"

            local["started_at"]   = new_started.isoformat()
            local["ended_at"]     = new_ended.isoformat()
            local["duration_min"] = new_duration
            local["id"]           = new_id

            # Backfill area_sqft from cloud when local has None
            if local.get("area_sqft") is None and best_cr.get("sqft") is not None:
                local["area_sqft"] = best_cr["sqft"]

            corrected += 1
            _LOGGER.debug(
                "MissionStore backfill: corrected %s → started_at=%s "
                "duration=%dmin (was %s, delta=%.0fs)",
                new_id, new_started.isoformat(),
                new_duration, old_started_str, delta_start,
            )

        if corrected:
            _LOGGER.info(
                "MissionStore backfill: corrected %d record(s) from cloud timestamps",
                corrected,
            )
        return corrected
