"""Data models for the Roomba+ integration.

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any

from homeassistant.config_entries import ConfigEntry

if TYPE_CHECKING:
    from roombapy import Roomba
    from .blocking_manager import BlockingManager
    from .cloud_coordinator import IrobotCloudCoordinator
    from .geometry_store import GeometryStore
    from .maintenance_store import MaintenanceStore
    from .mission_store import MissionStore          # v1.8.0 L1
    from .map_renderer import MapRenderer
    from .presence_manager import PresenceManager    # v1.8.0 L6
    from .zone_store import ZoneStore


class MapCapability(Enum):
    """Map rendering capability level of a robot.

    NONE:      600-series bump-and-run — no pose data, no map.
    EPHEMERAL: 900-series VSLAM — pose data available, map is per-mission only,
               no persistent pmaps. ZoneStore accumulates zones across missions.
    SMART:     i/s/j/m-series — pose data + persistent pmaps/regions.
               Cloud coordinator is created when credentials are available.
    """

    NONE = "none"
    EPHEMERAL = "ephemeral"
    SMART = "smart"


@dataclass
class RoombaData:
    """Runtime data stored in config_entry.runtime_data."""

    roomba: Roomba
    blid: str
    map_capability: MapCapability = MapCapability.NONE
    renderer: MapRenderer | None = None
    zone_store: ZoneStore | None = None
    geometry_store: GeometryStore | None = None
    maintenance_store: MaintenanceStore | None = None
    # Optional cloud coordinator — None when no credentials or non-SMART robot
    cloud_coordinator: IrobotCloudCoordinator | None = None
    # Optional blocking manager — None when CONF_BLOCKING_SENSORS not configured
    blocking_manager: BlockingManager | None = None  # v1.7.0 L5
    # v1.8.0 — Mission log, presence scheduling, and error state
    mission_store: MissionStore | None = None
    presence_manager: PresenceManager | None = None
    last_error_code: int | None = None      # persisted via MissionStore on load
    last_error_at: str | None = None        # ISO datetime string
    last_error_zone: str | None = None      # zone name at last error time

    def roomba_reported_state(self) -> dict[str, Any]:
        """Return the reported state dict from master_state."""
        return self.roomba.master_state.get("state", {}).get("reported", {})

    @property
    def has_cloud(self) -> bool:
        """True when the cloud coordinator is active and has fetched data."""
        return (
            self.cloud_coordinator is not None
            and self.cloud_coordinator.data is not None
        )


# Typed config entry — gives full IDE type safety throughout the integration
type RoombaConfigEntry = ConfigEntry[RoombaData]
