"""Presence-Aware Scheduling Manager for Roomba+.

Controls schedHold based on tracked person entity states. When all tracked
persons leave home, starts a configurable delay then unfreezes the cleaning
schedule (schedHold=False). When anyone returns, re-freezes it (schedHold=True).

The manager writes schedHold only when it is the one that unfroze it, tracked
via the is_managed_hold property. This prevents it from interfering with
manual schedule hold toggles.

Lifecycle (must be respected by callers):
  - Instantiate in async_setup_entry when presence_scheduling_enabled=True.
  - Call start() AFTER config_entry.runtime_data is set.
  - Store in entry.runtime_data.presence_manager.
  - Call cancel() in async_unload_entry — always.
  - Full HA reload is triggered on options change (no in-place restart needed).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING, Any

from homeassistant.core import HomeAssistant, callback

from .const import (
    CONF_AWAY_DELAY_MIN,
    CONF_PRESENCE_ENTITIES,
    CONF_PRESENCE_MODE,
    DEFAULT_AWAY_DELAY_MIN,
    DEFAULT_PRESENCE_MODE,
    EVENT_ALL_AWAY,
    EVENT_PERSON_DETECTED_DURING_CLEAN,
)

if TYPE_CHECKING:
    from .models import RoombaConfigEntry

_LOGGER = logging.getLogger(__name__)

# States that count as "home" — everything else is treated as "away"
_HOME_STATES = frozenset({"home", "on", "true"})
# Mission phases that indicate an active clean in progress
_ACTIVE_CLEANING_PHASES = frozenset({"run", "hmMidMsn", "evac"})


class PresenceManager:
    """Manage schedHold based on tracked person entity states."""

    def __init__(self, hass: HomeAssistant, config_entry: RoombaConfigEntry) -> None:
        self._hass = hass
        self._entry = config_entry
        self._cancel_listeners: list[Any] = []
        self._away_task: asyncio.Task | None = None
        # True when THIS manager set schedHold=False (unfreeze).
        # Used by is_managed_hold so the binary sensor can distinguish
        # presence-managed holds from manual ScheduleHoldSwitch toggles.
        self._managed_hold: bool = False
        self._did_unfreeze: bool = False  # True only when PM actually performed the unfreeze

    # ── Setup ─────────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Register state listeners and evaluate presence immediately.

        Must be called AFTER config_entry.runtime_data is set so the manager
        can read roomba state.
        """
        person_ids: list[str] = self._entry.options.get(CONF_PRESENCE_ENTITIES, [])
        if not person_ids:
            _LOGGER.warning(
                "PresenceManager: no presence entities configured — inactive"
            )
            return

        @callback
        def _on_state_changed(event: Any) -> None:
            if event.data.get("entity_id") in person_ids:
                self._hass.async_create_task(
                    self._evaluate_presence(),
                    name="roomba_plus_presence_eval",
                )

        unsub = self._hass.bus.async_listen("state_changed", _on_state_changed)
        self._cancel_listeners.append(unsub)

        # Evaluate on setup so initial state is applied immediately
        self._hass.async_create_task(self._evaluate_presence())
        _LOGGER.debug(
            "PresenceManager: started, tracking %s", person_ids
        )

    # ── Core logic ────────────────────────────────────────────────────────────

    async def _evaluate_presence(self) -> None:
        """Check all tracked persons and act on the result."""
        person_ids: list[str] = self._entry.options.get(CONF_PRESENCE_ENTITIES, [])
        if not person_ids:
            return  # safety guard: no entities configured
        all_away = all(
            (st := self._hass.states.get(eid)) is not None
            and st.state not in _HOME_STATES
            for eid in person_ids
        )
        if all_away:
            await self._handle_all_away()
        else:
            await self._handle_someone_home()

    async def _handle_all_away(self) -> None:
        """All persons away — start delay before unfreezing schedule."""
        if self._away_task is not None and not self._away_task.done():
            return  # delay already running

        delay_min: int = self._entry.options.get(
            CONF_AWAY_DELAY_MIN, DEFAULT_AWAY_DELAY_MIN
        )
        _LOGGER.debug(
            "PresenceManager: all away — %d min delay started", delay_min
        )
        self._away_task = self._hass.async_create_task(
            self._away_delay(delay_min * 60),
            name="roomba_plus_away_delay",
        )

    async def _away_delay(self, seconds: int) -> None:
        """Wait then unfreeze schedule or fire event depending on mode."""
        try:
            await asyncio.sleep(seconds)
        except asyncio.CancelledError:
            return

        mode = self._entry.options.get(CONF_PRESENCE_MODE, DEFAULT_PRESENCE_MODE)
        if mode == "away_only":
            await self._set_sched_hold(False)
            self._managed_hold = False
            self._did_unfreeze = True  # remember we performed the unfreeze
        else:
            # always_ask: fire event and let user automation handle it
            self._hass.bus.async_fire(EVENT_ALL_AWAY, {})
        self._away_task = None

    async def _handle_someone_home(self) -> None:
        """A person arrived — cancel delay and re-freeze if WE unfroze it."""
        if self._away_task and not self._away_task.done():
            self._away_task.cancel()
            self._away_task = None
            _LOGGER.debug("PresenceManager: arrival cancelled away delay")
            return

        data = self._entry.runtime_data
        state = data.roomba.master_state.get("state", {}).get("reported", {})

        if "schedHold" not in state:
            _LOGGER.debug(
                "PresenceManager: schedHold not in state — cannot write"
            )
            return

        # Only re-freeze if WE previously performed the unfreeze.
        # _did_unfreeze is set True only when _away_delay calls _set_sched_hold(False).
        # This prevents the PM from claiming ownership of a manual hold.
        if not state.get("schedHold", False) and self._did_unfreeze:
            await self._set_sched_hold(True)
            self._managed_hold = True
            self._did_unfreeze = False

            # Fire event if a clean is actively running
            phase = state.get("cleanMissionStatus", {}).get("phase", "")
            if phase in _ACTIVE_CLEANING_PHASES:
                self._hass.bus.async_fire(EVENT_PERSON_DETECTED_DURING_CLEAN, {})

    async def _set_sched_hold(self, value: bool) -> None:
        """Write schedHold preference to the robot.

        Guards against robots that don't support schedHold.
        Uses async_add_executor_job because roombapy's set_preference is
        synchronous (MQTT publish).
        """
        data = self._entry.runtime_data
        state = data.roomba.master_state.get("state", {}).get("reported", {})
        if "schedHold" not in state:
            _LOGGER.warning(
                "PresenceManager: schedHold not in robot state — cannot write"
            )
            return
        await self._hass.async_add_executor_job(
            data.roomba.set_preference, "schedHold", value
        )
        _LOGGER.info("PresenceManager: schedHold set to %s", value)

    # ── Public API ────────────────────────────────────────────────────────────

    @property
    def is_managed_hold(self) -> bool:
        """True when this manager is the source of the current schedHold=True."""
        return self._managed_hold

    def cancel(self) -> None:
        """Cancel all listeners and tasks. Idempotent — safe to call multiple times."""
        for unsub in self._cancel_listeners:
            try:
                unsub()
            except Exception:  # noqa: BLE001
                pass
        self._cancel_listeners.clear()

        if self._away_task and not self._away_task.done():
            self._away_task.cancel()
        self._away_task = None

        _LOGGER.debug("PresenceManager: cancelled")
