"""Service (action) handlers for the Roomba+ integration.

Registers and implements all domain services:
  - roomba_plus.clean_room   — room-targeted clean for SMART robots
  - roomba_plus.smart_start  — blocking-sensor-aware start
  - roomba_plus.reset_filter / reset_brush / reset_battery / reset_pad

Helper functions _resolve_pmapv_id and _resolve_rooms are kept here
alongside the handlers that use them.

Extracted from __init__.py (v2.0 refactor).

Generated by aurora@aurora-smart-home (ha-integration-dev skill)
https://github.com/tonylofgren/aurora-smart-home
"""
from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

import voluptuous as vol

from homeassistant.core import HomeAssistant, ServiceCall, SupportsResponse
from homeassistant.exceptions import ServiceValidationError
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers import entity_registry as er

from .const import (
    ATTR_ORDERED,
    ATTR_OVERRIDE_BLOCKING,
    ATTR_ROOM_NAME,
    ATTR_ROOMS,
    CONF_SMART_ZONE_DATA,
    DOMAIN,
    SERVICE_CLEAN_ROOM,
    SERVICE_RESET_BATTERY,
    SERVICE_RESET_BRUSH,
    SERVICE_RESET_FILTER,
    SERVICE_RESET_PAD,
    SERVICE_SMART_START,
)
from .models import MapCapability, RoombaConfigEntry, RoombaData

if TYPE_CHECKING:
    pass

_LOGGER = logging.getLogger(__name__)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _resolve_pmapv_id(state: dict, pmap_id: str) -> str | None:
    """Return the current user_pmapv_id for pmap_id from live MQTT state.

    Always reads state.pmaps at call time so the value is never stale.
    iRobot updates user_pmapv_id whenever the map is edited or retrained;
    a cached value silently causes the robot to reject the command.
    """
    for pmap in state.get("pmaps", []):
        if pmap_id in pmap:
            return pmap[pmap_id]
    return None


def _resolve_rooms(
    zone_data: dict[str, dict],
    room_names: list[str],
    state: dict,
    cloud_pmap_id: str | None = None,
) -> list[tuple[str, str]]:
    """Resolve room names to (region_id, pmap_id) tuples.

    Args:
        zone_data:      smart_zone_data from config_entry.options —
                        {region_id: {"name": str, "pmap_id": str}}
        room_names:     user-supplied room names from the service call.
        state:          live robot state — used to resolve pmap_id when the stored
                        value is empty (MQTT fallback).
        cloud_pmap_id:  authoritative pmap_id from the cloud coordinator.
                        When present this is preferred over the MQTT cascade.

    Returns:
        Ordered list of (region_id, pmap_id) matching each room name.

    Raises:
        ServiceValidationError: unknown name, unresolvable pmap_id, or
            rooms spanning more than one pmap_id.
    """
    index: dict[str, tuple[str, str]] = {}
    for rid, meta in zone_data.items():
        if not meta.get("name"):
            continue
        key = meta["name"].casefold()
        pmap_id = meta.get("pmap_id", "")
        if key in index:
            existing_rid, existing_pmap = index[key]
            if cloud_pmap_id and pmap_id == cloud_pmap_id:
                _LOGGER.warning(
                    "clean_room: duplicate room name '%s' across maps "
                    "(region %s from map %.8s overwrites region %s from map %.8s). "
                    "Delete the old Smart Map in the iRobot app to prevent this.",
                    meta["name"], rid, pmap_id, existing_rid, existing_pmap,
                )
                index[key] = (rid, pmap_id)
            else:
                _LOGGER.warning(
                    "clean_room: duplicate room name '%s' — keeping region %s "
                    "(region %s ignored, not from active map %.8s). "
                    "Delete the old Smart Map in the iRobot app.",
                    meta["name"], existing_rid, rid,
                    cloud_pmap_id[:8] if cloud_pmap_id else "unknown",
                )
        else:
            index[key] = (rid, pmap_id)

    resolved: list[tuple[str, str]] = []
    unknown: list[str] = []

    for name in room_names:
        match = index.get(name.casefold())
        if match is None:
            unknown.append(name)
        else:
            resolved.append(match)

    if unknown:
        raise ServiceValidationError(
            f"Unknown room(s): {', '.join(unknown)}. "
            f"Known rooms: {', '.join(meta['name'] for meta in zone_data.values() if meta.get('name'))}",
            translation_domain=DOMAIN,
            translation_key="rooms_not_found",
            translation_placeholders={"names": ", ".join(unknown)},
        )

    # Resolve empty pmap_ids — priority:
    #   0. cloud_pmap_id  — authoritative, immune to stale MQTT
    #   1. lastCommand.pmap_id
    #   2. cleanSchedule2[].cmd.pmap_id
    #   3. pmaps[0] key   — last resort
    last = state.get("lastCommand", {})
    pmaps: list[dict] = state.get("pmaps", [])
    fallback_pmap_id: str = (
        cloud_pmap_id
        or last.get("pmap_id")
        or next(
            (
                cmd.get("cmd", {}).get("pmap_id")
                for cmd in state.get("cleanSchedule2", [])
                if cmd.get("cmd", {}).get("pmap_id")
            ),
            None,
        )
        or (next(iter(pmaps[0]), None) if pmaps else None)
        or ""
    )
    resolved = [
        (rid, pmap_id if pmap_id else fallback_pmap_id)
        for rid, pmap_id in resolved
    ]

    pmap_ids = {pmap_id for _, pmap_id in resolved}
    if "" in pmap_ids:
        raise ServiceValidationError(
            "Could not resolve map ID (pmap_id) for one or more rooms. "
            "Ensure the robot has reported its map state via MQTT.",
            translation_domain=DOMAIN,
            translation_key="pmap_not_resolved",
        )
    if len(pmap_ids) > 1:
        raise ServiceValidationError(
            "All rooms must be on the same floor (same pmap). "
            f"Got rooms from maps: {', '.join(pmap_ids)}",
            translation_domain=DOMAIN,
            translation_key="rooms_different_floors",
            translation_placeholders={"pmap_ids": ", ".join(pmap_ids)},
        )

    return resolved


# ── Signal helper ─────────────────────────────────────────────────────────────

def _async_signal_entities(
    hass: HomeAssistant,
    entry_id: str,
    keys: list[str],
) -> None:
    """Force-refresh sensor/binary_sensor entities after non-MQTT state changes.

    Called after maintenance resets to immediately reflect the new baseline
    in timestamp sensors and L4 wear sensors, without waiting for the next
    MQTT push from the robot.
    """
    ent_reg = er.async_get(hass)
    entry = hass.config_entries.async_get_entry(entry_id)
    if entry is None:
        return
    data: RoombaData = entry.runtime_data
    robot_uid = f"roomba_plus_{data.blid}"
    for key in keys:
        for platform in ("sensor", "binary_sensor"):
            entity_id = ent_reg.async_get_entity_id(
                platform, DOMAIN, f"{robot_uid}_{key}"
            )
            if entity_id:
                current = hass.states.get(entity_id)
                if current:
                    hass.states.async_set(
                        entity_id,
                        current.state,
                        current.attributes,
                        force_update=True,
                    )
                break


# ── Service handlers ──────────────────────────────────────────────────────────

async def async_handle_clean_room(call: ServiceCall) -> None:
    """Handle the roomba_plus.clean_room service call.

    Resolves room names → region_ids, looks up the fresh user_pmapv_id from
    live MQTT state, and fires a region-targeted start command.

    Only works for MapCapability.SMART robots (i7 / s9 / j-series).
    """
    from . import roomba_reported_state

    hass = call.hass
    entity_ids: list[str] = call.data["entity_id"]
    room_names: list[str] = (
        [call.data[ATTR_ROOM_NAME]]
        if isinstance(call.data[ATTR_ROOM_NAME], str)
        else call.data[ATTR_ROOM_NAME]
    )
    ordered: bool = call.data[ATTR_ORDERED]

    ent_reg = er.async_get(hass)

    for entity_id in entity_ids:
        entry = ent_reg.async_get(entity_id)
        if entry is None:
            raise ServiceValidationError(f"Entity {entity_id} not found")

        config_entry: RoombaConfigEntry | None = hass.config_entries.async_get_entry(
            entry.config_entry_id
        )
        if config_entry is None:
            raise ServiceValidationError(f"No config entry for {entity_id}")

        data: RoombaData = config_entry.runtime_data

        if data.map_capability != MapCapability.SMART:
            raise ServiceValidationError(
                f"{entity_id} does not support Smart Map room cleaning. "
                "Only i7, s9, and j-series robots support this action.",
                translation_domain=DOMAIN,
                translation_key="not_smart_map",
            )

        zone_data: dict = config_entry.options.get(CONF_SMART_ZONE_DATA, {})

        if data.has_cloud:
            cc = data.cloud_coordinator
            cloud_zone_data: dict = {
                str(r["id"]): {"name": r["name"], "pmap_id": r["pmap_id"]}
                for r in cc.regions
                if r.get("id") and r.get("name")
            }
            cloud_zone_data.update({
                str(z["id"]): {"name": z["name"], "pmap_id": z["pmap_id"]}
                for z in cc.zones
                if z.get("id") and z.get("name")
            })
            zone_data = {**zone_data, **cloud_zone_data}

        if not zone_data:
            raise ServiceValidationError(
                "No rooms configured yet. Run a room-targeted clean via the "
                "iRobot app first, then assign names in the Roomba+ options.",
                translation_domain=DOMAIN,
                translation_key="no_rooms_configured",
            )

        state = roomba_reported_state(data.roomba)

        cloud_pmap_id: str | None = None
        if data.has_cloud:
            cloud_pmap_id = data.cloud_coordinator.active_pmap_id
            if cloud_pmap_id:
                _LOGGER.debug(
                    "clean_room: using cloud pmap_id %s for %s",
                    cloud_pmap_id[:12], entity_id,
                )

        not_ready: int = state.get("cleanMissionStatus", {}).get("notReady", 0)
        if not_ready & 64:
            raise ServiceValidationError(
                "The robot is currently updating its Smart Map. "
                "Wait for the update to complete (readiness sensor shows 'Ready'), "
                "then try again.",
                translation_domain=DOMAIN,
                translation_key="map_updating",
            )

        resolved = _resolve_rooms(zone_data, room_names, state, cloud_pmap_id)
        pmap_id = resolved[0][1]

        user_pmapv_id = _resolve_pmapv_id(state, pmap_id)
        if user_pmapv_id is None:
            _LOGGER.warning(
                "clean_room: pmap_id %s not found in live state for %s. "
                "The map may have been retrained. Re-run a mission via the app.",
                pmap_id, entity_id,
            )
            raise ServiceValidationError(
                f"Map {pmap_id} not found in robot state. "
                "The map may have been retrained — re-run a room mission via the app.",
                translation_domain=DOMAIN,
                translation_key="pmap_not_found",
            )

        params = {
            "ordered": 1 if ordered else 0,
            "pmap_id": pmap_id,
            "regions": [
                {
                    "region_id": rid,
                    "type": "rid",
                    "params": {"noAutoPasses": False, "twoPass": False},
                }
                for rid, _ in resolved
            ],
        }

        _LOGGER.info(
            "clean_room: %s → regions=%s pmap=%s pmapv=%s (not sent)",
            entity_id,
            [rid for rid, _ in resolved],
            pmap_id[:12],
            user_pmapv_id[:12] if user_pmapv_id else "none",
        )

        await hass.async_add_executor_job(
            data.roomba.send_command, "start", params
        )

    return {}


async def async_handle_smart_start(call: ServiceCall) -> None:
    """Handle roomba_plus.smart_start with blocking-sensor gate."""
    hass = call.hass
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]
    rooms: list[str] | None = call.data.get(ATTR_ROOMS)
    override: bool = call.data.get(ATTR_OVERRIDE_BLOCKING, False)

    ent_reg = er.async_get(hass)

    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            raise ServiceValidationError(
                f"Entity {eid} not found",
                translation_domain=DOMAIN,
                translation_key="entity_not_found",
            )
        config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            raise ServiceValidationError(f"No config entry for {eid}")

        data: RoombaData = config_entry.runtime_data
        if rooms and data.map_capability != MapCapability.SMART:
            raise ServiceValidationError(
                f"{eid} does not support room targeting — "
                "only i7, s9, and j-series robots support this.",
                translation_domain=DOMAIN,
                translation_key="not_smart_map",
            )
        if data.blocking_manager is not None:
            await data.blocking_manager.check_and_start(rooms, override)
        elif rooms:
            await hass.services.async_call(
                DOMAIN,
                SERVICE_CLEAN_ROOM,
                {"entity_id": eid, ATTR_ROOM_NAME: rooms},
                blocking=True,
            )
        else:
            await hass.async_add_executor_job(data.roomba.start)


async def _handle_reset_service(
    hass: HomeAssistant, call: ServiceCall, part: str
) -> None:
    """Handle roomba_plus.reset_{filter|brush|battery|pad}."""
    entity_ids: list[str] = call.data.get("entity_id", [])
    if isinstance(entity_ids, str):
        entity_ids = [entity_ids]

    ent_reg = er.async_get(hass)

    for eid in entity_ids:
        entry_reg = ent_reg.async_get(eid)
        if entry_reg is None:
            _LOGGER.warning("reset_%s: entity not found: %s", part, eid)
            continue
        config_entry = hass.config_entries.async_get_entry(entry_reg.config_entry_id)
        if config_entry is None:
            _LOGGER.warning("reset_%s: config entry not found for %s", part, eid)
            continue

        data: RoombaData = config_entry.runtime_data
        if data.maintenance_store is None:
            raise ServiceValidationError(
                f"Maintenance store not available for {eid}",
                translation_domain=DOMAIN,
                translation_key="maintenance_store_unavailable",
            )

        state = data.roomba_reported_state()
        _bbrun   = state.get("bbrun", {})
        _runtime = state.get("runtimeStats", {})
        current_hr: int = _bbrun.get("hr") or _runtime.get("hr") or 0
        getattr(data.maintenance_store, f"reset_{part}")(current_hr)
        await data.maintenance_store.async_save(hass, config_entry.entry_id)
        _async_signal_entities(hass, config_entry.entry_id, [
            "filter_last_replaced",
            "brush_last_replaced",
            "pad_last_replaced",
            "battery_last_replaced",
            "filter_wear_rate",
            "brush_wear_rate",
            "pad_wear_rate",
            "filter_days_until_due",
            "brush_days_until_due",
            "pad_days_until_due",
        ])
        _LOGGER.info("reset_%s: executed for %s at %dh", part, eid, current_hr)


# ── Registration ──────────────────────────────────────────────────────────────

def async_register_services(hass: HomeAssistant) -> None:
    """Register all Roomba+ domain services. Safe to call multiple times.

    Each service is guarded by has_service() — only registers on first call,
    subsequent entries reuse the same handlers.
    """
    _RESET_SCHEMA = vol.Schema({vol.Required("entity_id"): cv.entity_ids})

    if not hass.services.has_service(DOMAIN, SERVICE_CLEAN_ROOM):
        hass.services.async_register(
            DOMAIN,
            SERVICE_CLEAN_ROOM,
            async_handle_clean_room,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_ids,
                vol.Required(ATTR_ROOM_NAME): vol.Any(
                    cv.string,
                    vol.All(cv.ensure_list, [cv.string]),
                ),
                vol.Optional(ATTR_ORDERED, default=True): cv.boolean,
            }),
            supports_response=SupportsResponse.OPTIONAL,
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_CLEAN_ROOM)

    if not hass.services.has_service(DOMAIN, SERVICE_SMART_START):
        hass.services.async_register(
            DOMAIN,
            SERVICE_SMART_START,
            async_handle_smart_start,
            schema=vol.Schema({
                vol.Required("entity_id"): cv.entity_ids,
                vol.Optional(ATTR_ROOMS): vol.All(cv.ensure_list, [cv.string]),
                vol.Optional(ATTR_OVERRIDE_BLOCKING, default=False): cv.boolean,
            }),
        )
        _LOGGER.debug("Registered %s.%s action", DOMAIN, SERVICE_SMART_START)

    for _part in ("filter", "brush", "battery", "pad"):
        svc = f"reset_{_part}"
        if not hass.services.has_service(DOMAIN, svc):
            _p = _part

            async def _make_reset_handler(
                call: ServiceCall, p: str = _p
            ) -> None:
                await _handle_reset_service(call.hass, call, p)

            hass.services.async_register(
                DOMAIN,
                svc,
                _make_reset_handler,
                schema=_RESET_SCHEMA,
            )


def async_remove_services(hass: HomeAssistant) -> None:
    """Remove all Roomba+ domain services (called when last entry unloads)."""
    for svc in (
        SERVICE_CLEAN_ROOM,
        SERVICE_SMART_START,
        "reset_filter",
        "reset_brush",
        "reset_battery",
        "reset_pad",
    ):
        if hass.services.has_service(DOMAIN, svc):
            hass.services.async_remove(DOMAIN, svc)
